CITIES_RUSSAIN = [
    "Астрахань",
    "Барнаул",
    "Белгород",
    "Брянск",
    "Владивосток",
    "Волгоград",
    "Воронеж",
    "Екатеринбург",
    "Иваново",
    "Ижевск",
    "Иркутск",
    "Казань",
    "Калининград",
    "Кемерово",
    "Киров",
    "Краснодар",
    "Красноярск",
    "Курск",
    "Липецк",
    "Махачкала",
    "Москва",
    "Нижний Новгород",
    "Новокузнецк",
    "Новосибирск",
    "Омск",
    "Оренбург",
    "Пенза",
    "Пермь",
    "Ростов-на-Дону",
    "Рязань",
    "Самара",
    "Саратов",
    "Санкт-Петербург",
    "Сочи",
    "Ставрополь",
    "Сургут",
    "Тверь",
    "Томск",
    "Тула",
    "Тюмень",
    "Улан-Удэ",
    "Ульяновск",
    "Уфа",
    "Хабаровск",
    "Чебоксары",
    "Челябинск",
    "Ярославль"
]
CITIES_ENGLISH = [
    "Astrakhan",
    "Barnaul",
    "Belgorod",
    "Bryansk",
    "Vladivostok",
    "Volgograd",
    "Voronezh",
    "Yekaterinburg",
    "Ivanovo",
    "Izhevsk",
    "Irkutsk",
    "Kazan",
    "Kaliningrad",
    "Kemerovo",
    "Kirov",
    "Krasnodar",
    "Krasnoyarsk",
    "Kursk",
    "Lipetsk",
    "Makhachkala",
    "Moscow",
    "Nizhny Novgorod",
    "Novokuznetsk",
    "Novosibirsk",
    "Omsk",
    "Orenburg",
    "Penza",
    "Perm",
    "Rostov-on-Don",
    "Ryazan",
    "Samara",
    "Saratov",
    "Saint Petersburg",
    "Sochi",
    "Stavropol",
    "Surgut",
    "Tver",
    "Tomsk",
    "Tula",
    "Tyumen",
    "Ulan-Ude",
    "Ulyanovsk",
    "Ufa",
    "Khabarovsk",
    "Cheboksary",
    "Chelyabinsk",
    "Yaroslavl"
]

CITIES_ENGLISH_RUSSAIN = {
    "Astrakhan": "Астрахань",
    "Barnaul": "Барнаул",
    "Belgorod": "Белгород",
    "Bryansk": "Брянск",
    "Vladivostok": "Владивосток",
    "Volgograd": "Волгоград",
    "Voronezh": "Воронеж",
    "Yekaterinburg": "Екатеринбург",
    "Ivanovo": "Иваново",
    "Izhevsk": "Ижевск",
    "Irkutsk": "Иркутск",
    "Kazan": "Казань",
    "Kaliningrad": "Калининград",
    "Kemerovo": "Кемерово",
    "Kirov": "Киров",
    "Krasnodar": "Краснодар",
    "Krasnoyarsk": "Красноярск",
    "Kursk": "Курск",
    "Lipetsk": "Липецк",
    "Makhachkala": "Махачкала",
    "Moscow": "Москва",
    "Nizhny Novgorod": "Нижний Новгород",
    "Novokuznetsk": "Новокузнецк",
    "Novosibirsk": "Новосибирск",
    "Omsk": "Омск",
    "Orenburg": "Оренбург",
    "Penza": "Пенза",
    "Perm": "Пермь",
    "Rostov-on-Don": "Ростов-на-Дону",
    "Ryazan": "Рязань",
    "Samara": "Самара",
    "Saratov": "Саратов",
    "Saint Petersburg": "Санкт-Петербург",
    "Sochi": "Сочи",
    "Stavropol": "Ставрополь",
    "Surgut": "Сургут",
    "Tver": "Тверь",
    "Tomsk": "Томск",
    "Tula": "Тула",
    "Tyumen": "Тюмень",
    "Ulan-Ude": "Улан-Удэ",
    "Ulyanovsk": "Ульяновск",
    "Ufa": "Уфа",
    "Khabarovsk": "Хабаровск",
    "Cheboksary": "Чебоксары",
    "Chelyabinsk": "Челябинск",
    "Yaroslavl": "Ярославль"
}
CITIES_RUSSAIN_ENGLISH = {
    "Астрахань": "Astrakhan",
    "Барнаул": "Barnaul",
    "Белгород": "Belgorod",
    "Брянск": "Bryansk",
    "Владивосток": "Vladivostok",
    "Волгоград": "Volgograd",
    "Воронеж": "Voronezh",
    "Екатеринбург": "Yekaterinburg",
    "Иваново": "Ivanovo",
    "Ижевск": "Izhevsk",
    "Иркутск": "Irkutsk",
    "Казань": "Kazan",
    "Калининград": "Kaliningrad",
    "Кемерово": "Kemerovo",
    "Киров": "Kirov",
    "Краснодар": "Krasnodar",
    "Красноярск": "Krasnoyarsk",
    "Курск": "Kursk",
    "Липецк": "Lipetsk",
    "Махачкала": "Makhachkala",
    "Москва": "Moscow",
    "Нижний Новгород": "Nizhny Novgorod",
    "Новокузнецк": "Novokuznetsk",
    "Новосибирск": "Novosibirsk",
    "Омск": "Omsk",
    "Оренбург": "Orenburg",
    "Пенза": "Penza",
    "Пермь": "Perm",
    "Ростов-на-Дону": "Rostov-on-Don",
    "Рязань": "Ryazan",
    "Самара": "Samara",
    "Саратов": "Saratov",
    "Санкт-Петербург": "Saint Petersburg",
    "Сочи": "Sochi",
    "Ставрополь": "Stavropol",
    "Сургут": "Surgut",
    "Тверь": "Tver",
    "Томск": "Tomsk",
    "Тула": "Tula",
    "Тюмень": "Tyumen",
    "Улан-Удэ": "Ulan-Ude",
    "Ульяновск": "Ulyanovsk",
    "Уфа": "Ufa",
    "Хабаровск": "Khabarovsk",
    "Чебоксары": "Cheboksary",
    "Челябинск": "Chelyabinsk",
    "Ярославль": "Yaroslavl"
}